### ISSUE TITLE
Support for exporting data to IoT Topics

### ISSUE THREAD

**Issue by QuantumLove** [aws-greengrass/aws-greengrass-stream-manager-sdk-js#2]
Stream Manager has nice features, I would like to be able to use them with the messages I publish to IoT Topics.

## Use Case

I need to overwrite the thingName in the incoming data, since I don't want to rely on the device telling me the truth about its identity.
Right now I do this by using an IoT Rule SQL statement.

If I let it just send data directly to IoT Analytics or Kinesis I cannot confirm where the data is coming from as the device write anything it wants in the message.
PS: No *npm* release for this package?

**Comment by sushantAtAws** [comment]
Hi @QuantumLove 
I am not sure what the use case. Can you please elaborate more on this? What is the data flow? Are the messages coming from client devices and dumped into the Stream Manager?
