### ISSUE TITLE
Name of the Stream manager name cannot hold .log

### ISSUE THREAD

**Issue by rubensalazarblq** [aws-greengrass/aws-greengrass-stream-manager-sdk-js#4]
If I create a Stream with the name:

filter.log.day.machine.txt

No error is generated during the creation but when we try to append a message an error is logged:

Error: java.io.IOException: java.util.concurrent.ExecutionException: java.nio.file.NoSuchFileException: /var/greengrass/streams/filter.index.-day.machine.txt/0000000000000000000.index

That breaks the StreamManager component and does not allow us to make a new deployment, looks like the core tries to access to that folder that doesn't exist

**Comment by MikeDombo** [comment]
Hello @rubensalazarblq,

Can you please provide the full log which includes this error?

Please also provide the configuration for the Stream manager component.

What version of Greengrass specifically are you using? If you are using Greengrass V2, what version of Stream manager are you using?

**Comment by rubensalazarblq** [comment]
Hi @MikeDombo  thanks for your quick answer.. let me attach the logs and the information that you request.


GG V2 - amazon/aws-iot-greengrass:2.5.3-0

Component Name: aws.greengrass.StreamManager
    Version: 2.0.14
    State: RUNNING

[aws.greengrass.StreamManager - Copy -  Error.log](https://github.com/aws-greengrass/aws-greengrass-stream-manager-sdk-js/files/7974970/aws.greengrass.StreamManager.-.Copy.-.Error.log) Main error that locks the deploy for the stream manager.

I solved it replacing the main folder:

sudo mkdir /var/greengrass/streams
sudo chown ggc_user /var/greengrass/streams
sudo chmod 700 /var/greengrass/streams

That's allows me to deploy again my component

And my lambda component' log: 
[gg-lambda-logs-rsalazar_2022_01_27_20_3.log](https://github.com/aws-greengrass/aws-greengrass-stream-manager-sdk-js/files/7975012/gg-lambda-logs-rsalazar_2022_01_27_20_3.log)

**Comment by MikeDombo** [comment]
Please provide the configuration of the stream manager component too. Stream manager does not write to `/var/greengrass/streams` by default. So that means that you must have set that to be the Stream manager directory, right? Why have you set it to that location, is there a particular reason why the default location does not work?


> Main error that locks the deploy for the stream manager.

What do you mean that it "locks the deployment for stream manager"? When a component is in the BROKEN state, you can absolutely still deploy, however, if it remains broken even after the deployment, the deployment will rollback to the previous state if configured to. The default is to rollback when a deployment fails, however you may choose to not rollback on failure.

**Comment by rubensalazarblq** [comment]
Stream Manager config:

 ```
await client.createMessageStream(
      new MessageStreamDefinition()
        .withName(streamName)
        .withStrategyOnFull(StrategyOnFull.OverwriteOldestData)
        .withPersistence(Persistence.File)
        .withFlushOnWrite(false)
        .withMaxSize(268435456)
        .withStreamSegmentSize(16777216)
    );
```
I don't know the reason why the default location does not work, but you are right about the rollback, it's my default setting that makes the rollback but the deployment just logs that the Stream Manager component is broken, and due the deployment fails it tries to makes the rolleback but there is not healthy component to run again, so I was stuck and my core was unhealthy with the broken componet. Once that I changed the default folder, it allows me to deploy a healthy component.

**Comment by MikeDombo** [comment]
For the config, I mean the configuration of the stream manager component itself. You said that you changed the directory structure. Please provide the configuration which you were using that did not work as well as the one which did work.

The missing file is not really a missing file, but more likely the missing path. The path is created when the stream is created using createMessageStream. Did you delete any directories, or move them manually?

**Comment by rubensalazarblq** [comment]
Sorry my bad, I did not change the default folder, I just create the folder and add grants to it.
```
sudo mkdir /var/greengrass/streams
sudo chown ggc_user /var/greengrass/streams
sudo chmod 700 /var/greengrass/streams
```
The configuration of my component is the default:
```
{
  "STREAM_MANAGER_ENABLE_LOCK_ON_METADATA_STORE": "false",
  "STREAM_MANAGER_AUTHENTICATE_CLIENT": "true",
  "STREAM_MANAGER_EXPORTER_THREAD_POOL_SIZE": "5",
  "port": "",
  "STREAM_MANAGER_SERVER_PORT": "8088",
  "JVM_ARGS": "",
  "STREAM_MANAGER_STORE_ROOT_DIR": ".",
  "LOG_LEVEL": "INFO",
  "STREAM_MANAGER_EXPORTER_MAX_BANDWIDTH": "2147483647",
  "STREAM_MANAGER_EXPORTER_S3_DESTINATION_MULTIPART_UPLOAD_MIN_PART_SIZE_BYTES": "5242880"
}
```

**Comment by MikeDombo** [comment]
Greengrass does not use the directory `/var/greengrass/streams`, so do you know how that path came to be used?

**Comment by rubensalazarblq** [comment]
Sorry @MikeDombo a co-worker changes the default for the component on the deployment, because he had a similar error and tought that starting with a fresh directory would solve it.

![image](https://user-images.githubusercontent.com/34073336/152020574-40bf54ad-0d11-45a3-95ca-ffd31902abf9.png)

but at the end we did not touch that directory with any script or software. So StreamManager is the only one that works with it.

**Comment by MikeDombo** [comment]
When a directory is provided, it has to be setup correctly, meaning that the user running Stream manager (in your case ggc_user) needs permission on the directory. Due to how linux works, the user also needs read and execute permissions on all parent paths ie. `/`, `/var`, `/var/greengrass`, and `/var/greengrass/streams`. 

Everything is currently working for you, is that right?

**Comment by rubensalazarblq** [comment]
Yes.. right now is working with the new directory and the grants that I setup.

Also I changed the name of my Stream from "filter.log.filename.txt" to "f-log.filename.txt" my lambda component works properly, I'm able to create the Stream and append a message.

**Comment by MikeDombo** [comment]
Now that the directories are working properly even with that fix, you say the stream name `filter.log.filename.txt` would cause issues? Is that something that you've tried?

**Comment by MikeDombo** [comment]
I have verified the issue. We will work to fix this in stream manager, until then please avoid using a stream name with `.log`

**Comment by rubensalazarblq** [comment]
> I have verified the issue. We will work to fix this in stream manager, until then please avoid using a stream name with `.log`

Thanks for you help!!

**Comment by MikeDombo** [comment]
Sorry this fell through the cracks and I forgot to close it. This issue was resolved in newer versions of stream manager
